name_1 = input("Введите имя: ")
surname_1 = input("Введите фамилию: ")
var_1 = int(input("Введите номер варианта: "))
quest = int(input("Введите номер задания: "))
answ = int(input("Введите ответ: "))
print(f"{name_1} {surname_1} выполнил вариант {var_1}. В задании {quest} он получил ответ {answ}.")
